### ISSUE TITLE
additional documentation

### ISSUE THREAD

**Issue by adrizos** [vdemedes/node-google-images#28]
Hi there!
I followed all of your set up instructions. Just curious, I'm trying to use this to get a string link to a random image from a  google search query from the first page of the results. Just curious if you have any tips on how to access this once the search is made. Thanks!

**Comment by adrizos** [comment]
```
client.search('chirping crickets meme')
        .then(images => {
            /*
            [{
            "url": "http://steveangello.com/boss.jpg",
            "type": "image/jpeg",
            "width": 1024,
            "height": 768,
            "size": 102451,
            "thumbnail": {
            "url": "http://steveangello.com/thumbnail.jpg",
            "width": 512,
            "height": 512
                }
            }]
            */
            });

        var imageLink = client.list.items[randIndex].image.thumbnailLink;

        //create response
        var newTweet = '@' + screenName + imageLink + count;
```

I looked in the google api and it appeared that it might save the results in an items list?

**Comment by vadimdemedes** [comment]
Hey! I don't think I understand what's the issue here, your code seems fine and it should work. Could you explain what's not working?

**Comment by adrizos** [comment]
Im getting "TypeError: Cannot read property 'items' of undefined" for the var imageLink line. 
Im sort of guessing on what that line should even be based on reading through the google api... 

So my two questions are really - is my .search the right way to go here and secondly if you have more info about how to actually access the search data that would be really helpful. I would love to see some examples for accessing various relevant data pieces. Thanks so much for the quick response.

**Comment by vadimdemedes** [comment]
I don't know what `client.list` is, but I guess it should be replaced with `images`, since that's the variable that contains results.

**Comment by adrizos** [comment]
Ive taken your advice and it keeps telling me images is not defined...
Could you post an example of accessing various data from the search results. Thanks man!

**Comment by vadimdemedes** [comment]
There's an example in the readme: https://github.com/vadimdemedes/google-images#usage.

**Comment by adrizos** [comment]
So, in that example. You have some code commented out, which I thought was just showing an example of the mapping inside of the images variable? But maybe Im wrong about that, should I be doing some work in there? 

`client.search('Steve Angello')
	.then(images => {
		/*
		[{
			"url": "http://steveangello.com/boss.jpg",
			"type": "image/jpeg",
			"width": 1024,
			"height": 768,
			"size": 102451,
			"thumbnail": {
				"url": "http://steveangello.com/thumbnail.jpg",
				"width": 512,
				"height": 512
			}
		}]
		 */
	});`

**Comment by vadimdemedes** [comment]
That's an example of the contents of `images` variable.
