### ISSUE TITLE
_Failed to minify the code from this file:  ./node_modules/google-images/index.js:6_  (google-images@2.1.0)

### ISSUE THREAD

**Issue by Rajeevak** [vdemedes/node-google-images#32]
Could not build App using Create-React-App. Getting the following error while building production build. Developer build is working.
_Failed to minify the code from this file:  ./node_modules/google-images/index.js:6_

**Comment by vadimdemedes** [comment]
I have never used create-react-app, so I can't be 100% sure about this, but most likely it's a problem related to uglifyjs not being able to minify ES6 code. Solution is to allow transpilation of all node_modules or only `google-images`.
