### ISSUE TITLE
Webpack Error: Module not found

### ISSUE THREAD

**Issue by pmochine** [vdemedes/node-google-images#33]
I tried everything like

     const GoogleImages = require('google-images');
     window.GoogleImages = require('google-images');
     import GoogleImages from 'google-images';

Nothing works. I get the error:

     ERROR in ./node_modules/google-images/node_modules/got/index.js
     Module not found: Error: Can't resolve './package' in 
     '/Users/shadrix/Dropbox/Business/insta/Website_W_Laravel/insta/node_modules/google-images/node_modules/got'
      @ ./node_modules/google-images/node_modules/got/index.js 19:12-32
      @ ./node_modules/google-images/index.js
      @ ./resources/assets/js/bootstrap.js
      @ ./resources/assets/js/app.js
      @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

**Comment by agursky** [comment]
I was able to get around this. The problem wasn't with google-images, it is with one of its dependences - 'got'. Navigate to the 'got' folder in 'node-modules'. In node-modules/got/index.js on line 19 change:`const pkg = require('./package);` to `const pkg = require('./package.json);`. That fixes it. If you still have the issue, you should make sure your webpack file is configured correctly.

**Comment by vadimdemedes** [comment]
Good catch, @agursky! Although I wouldn't recommend using this module in a client-side app, as I think it would add quite a few kilobytes to the bundle size.
