### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by LiamWiddop** [vdemedes/node-google-images#38]
**The bug**
Just letting you know that you're using `setImmediate` in `got/index.js`, which throws the following error: `ReferenceError: setImmediate is not defined`

setImmediate() is a [non-standard API](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate#Browser_compatibility) and shouldn't be used in frontend code.

**How to fix**
Simply just exchanging it with setTimeout(func, 0);

**For users in the interim**
Users can get around this by adding the following within your html <head>: 
```
<script>
  const setImmediate = (func)=>{setTimeout(func,0001)};
</script>
``

**Comment by vadimdemedes** [comment]
This module wasn't meant to be used in the browser.
