### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by magliocchetti** [vdemedes/node-google-images#41]
[DELETED]
++++++++++
EDIT: Please see: https://github.com/vadimdemedes/google-images/pull/42#issue-1306975824

**Comment by obrobrio2000** [comment]
I have proposed an update that also solves this issue. Please take a look at PR #42 :)

**Comment by obrobrio2000** [comment]
Project seems dead from 2017 so I'll close this and create a fork instead...

**Comment by obrobrio2000** [comment]
Apparently this project is dead since 2017 and even other PRs haven't been merged since then. I'll close this (and #41) and maintain a fork instead.

_Originally posted by @obrobrio2000 in https://github.com/vadimdemedes/google-images/issues/42#issuecomment-1190851198_
