### ISSUE TITLE
Scraping option

### ISSUE THREAD

**Issue by bluejamesbond** [vdemedes/node-google-images#7]
Not sure which way this library is learning, but you can get a hard scrape of the google images with the follow script. This means that it will visit the images homepage and scrape for images from there.

The script is short and can be found here. https://github.com/bluejamesbond/cs373-idb/blob/gh-pages/scripts/google/images.js (made for educational purposes)

It would be interesting to see you have two options: (1) the rest protocol and the (2) hard scrape format. The hard scrape if used correctly (as to not trigger the google scrape detector) will allow you to get unlimited images.

**Comment by vdemedes** [comment]
First of all, having 2 ways of doing exact same thing is not a good choice to implement in a single-purpose module. 

Also, scraping is mot reliable. This library will have to be updated every time Google changes their markup.
